/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as ServicoIdRouteImport } from './routes/servico.$id'
import { Route as DashboardMensagensRouteImport } from './routes/dashboard.mensagens'
import { Route as DashboardFavoritosRouteImport } from './routes/dashboard.favoritos'
import { Route as DashboardAnunciosIndexRouteImport } from './routes/dashboard.anuncios.index'
import { Route as DashboardAnunciosNovoRouteImport } from './routes/dashboard.anuncios.novo'
import { Route as DashboardAnunciosIdEditarRouteImport } from './routes/dashboard.anuncios.$id.editar'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const ServicoIdRoute = ServicoIdRouteImport.update({
  id: '/servico/$id',
  path: '/servico/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMensagensRoute = DashboardMensagensRouteImport.update({
  id: '/mensagens',
  path: '/mensagens',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFavoritosRoute = DashboardFavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnunciosIndexRoute = DashboardAnunciosIndexRouteImport.update({
  id: '/anuncios/',
  path: '/anuncios/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnunciosNovoRoute = DashboardAnunciosNovoRouteImport.update({
  id: '/anuncios/novo',
  path: '/anuncios/novo',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnunciosIdEditarRoute =
  DashboardAnunciosIdEditarRouteImport.update({
    id: '/anuncios/$id/editar',
    path: '/anuncios/$id/editar',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/favoritos': typeof DashboardFavoritosRoute
  '/dashboard/mensagens': typeof DashboardMensagensRoute
  '/servico/$id': typeof ServicoIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/anuncios/novo': typeof DashboardAnunciosNovoRoute
  '/dashboard/anuncios/': typeof DashboardAnunciosIndexRoute
  '/dashboard/anuncios/$id/editar': typeof DashboardAnunciosIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard/favoritos': typeof DashboardFavoritosRoute
  '/dashboard/mensagens': typeof DashboardMensagensRoute
  '/servico/$id': typeof ServicoIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/anuncios/novo': typeof DashboardAnunciosNovoRoute
  '/dashboard/anuncios': typeof DashboardAnunciosIndexRoute
  '/dashboard/anuncios/$id/editar': typeof DashboardAnunciosIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/favoritos': typeof DashboardFavoritosRoute
  '/dashboard/mensagens': typeof DashboardMensagensRoute
  '/servico/$id': typeof ServicoIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/anuncios/novo': typeof DashboardAnunciosNovoRoute
  '/dashboard/anuncios/': typeof DashboardAnunciosIndexRoute
  '/dashboard/anuncios/$id/editar': typeof DashboardAnunciosIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard/favoritos'
    | '/dashboard/mensagens'
    | '/servico/$id'
    | '/dashboard/'
    | '/dashboard/anuncios/novo'
    | '/dashboard/anuncios/'
    | '/dashboard/anuncios/$id/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard/favoritos'
    | '/dashboard/mensagens'
    | '/servico/$id'
    | '/dashboard'
    | '/dashboard/anuncios/novo'
    | '/dashboard/anuncios'
    | '/dashboard/anuncios/$id/editar'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard/favoritos'
    | '/dashboard/mensagens'
    | '/servico/$id'
    | '/dashboard/'
    | '/dashboard/anuncios/novo'
    | '/dashboard/anuncios/'
    | '/dashboard/anuncios/$id/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ServicoIdRoute: typeof ServicoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/servico/$id': {
      id: '/servico/$id'
      path: '/servico/$id'
      fullPath: '/servico/$id'
      preLoaderRoute: typeof ServicoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/mensagens': {
      id: '/dashboard/mensagens'
      path: '/mensagens'
      fullPath: '/dashboard/mensagens'
      preLoaderRoute: typeof DashboardMensagensRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/favoritos': {
      id: '/dashboard/favoritos'
      path: '/favoritos'
      fullPath: '/dashboard/favoritos'
      preLoaderRoute: typeof DashboardFavoritosRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/anuncios/': {
      id: '/dashboard/anuncios/'
      path: '/anuncios'
      fullPath: '/dashboard/anuncios/'
      preLoaderRoute: typeof DashboardAnunciosIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/anuncios/novo': {
      id: '/dashboard/anuncios/novo'
      path: '/anuncios/novo'
      fullPath: '/dashboard/anuncios/novo'
      preLoaderRoute: typeof DashboardAnunciosNovoRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/anuncios/$id/editar': {
      id: '/dashboard/anuncios/$id/editar'
      path: '/anuncios/$id/editar'
      fullPath: '/dashboard/anuncios/$id/editar'
      preLoaderRoute: typeof DashboardAnunciosIdEditarRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardFavoritosRoute: typeof DashboardFavoritosRoute
  DashboardMensagensRoute: typeof DashboardMensagensRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAnunciosNovoRoute: typeof DashboardAnunciosNovoRoute
  DashboardAnunciosIndexRoute: typeof DashboardAnunciosIndexRoute
  DashboardAnunciosIdEditarRoute: typeof DashboardAnunciosIdEditarRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardFavoritosRoute: DashboardFavoritosRoute,
  DashboardMensagensRoute: DashboardMensagensRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAnunciosNovoRoute: DashboardAnunciosNovoRoute,
  DashboardAnunciosIndexRoute: DashboardAnunciosIndexRoute,
  DashboardAnunciosIdEditarRoute: DashboardAnunciosIdEditarRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ServicoIdRoute: ServicoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
